name: u_cicd_apigw

on:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  # prevent concurrent executions of this workflow
  # we need the dev update to complete before promoting 
  group: ${{ github.workflow }}

jobs:
  update-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    # only runs against commits to the master branch
    if: github.ref == 'refs/heads/master'
    environment: lab
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
        - name: Deploy to lab
        run: ./gateway_import_export_utils.sh import Petstore ${{ secrets.APIGW_URL }} ${{ secrets.APIGW_USERNAME }} ${{ secrets.APIGW_PASSWORD }}

  promote-to-staging:
    runs-on: ubuntu-latest
    # only run for tags
    if: contains(github.ref, 'refs/tags/')
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - id: api-info
        # get the api name and version from the swagger spec
        # we need to set these as variables to use them as input in the next step
        run: |
          API_NAME=$(jq '.info.title' swagger.json | tr -d '"')
          API_VERSION=$(jq '.info.version' swagger.json | tr -d '"')
          echo "::set-output name=api-name::${API_NAME}"
          echo "::set-output name=api-version::${API_VERSION}"
      - uses: jiridj/wm-apigw-actions-promote-api@v1
        with: 
          apigw-url: ${{ secrets.APIGW_URL }}
          apigw-username: ${{ secrets.APIGW_USERNAME }}
          apigw-password: ${{ secrets.APIGW_PASSWORD }}
          api-name: ${{ steps.api-info.outputs.api-name }}
          api-version: ${{ steps.api-info.outputs.api-version }}
          stage-name: staging
          debug: ${{ secrets.ACTIONS_STEP_DEBUG }} 

  promote-to-prod:
    runs-on: ubuntu-latest
    needs: [ promote-to-staging ]
    # only run for tags
    if: contains(github.ref, 'refs/tags/')
    environment: production
    steps:
      - uses: actions/checkout@v3
      - id: api-info
        # get the api name and version from the swagger spec
        # we need to set these as variables to use them as input in the next step
        run: |
          API_NAME=$(jq '.info.title' swagger.json | tr -d '"')
          API_VERSION=$(jq '.info.version' swagger.json | tr -d '"')
          echo "::set-output name=api-name::${API_NAME}"
          echo "::set-output name=api-version::${API_VERSION}"
      - uses: jiridj/wm-apigw-actions-promote-api@v1
        with: 
          apigw-url: ${{ secrets.APIGW_URL }}
          apigw-username: ${{ secrets.APIGW_USERNAME }}
          apigw-password: ${{ secrets.APIGW_PASSWORD }}
          api-name: ${{ steps.api-info.outputs.api-name }}
          api-version: ${{ steps.api-info.outputs.api-version }}
          stage-name: production
          debug: ${{ secrets.ACTIONS_STEP_DEBUG }}
